### ISSUE TITLE
ノド・小口の余白調整の修正

### ISSUE THREAD

**Issue by mitsuharu** [mitsuharu/vivliostyle-theme-iosdc-pamphlet#3]
https://qiita.com/u1f992/items/8aa60c0cce645a5929ae

**Comment by mitsuharu** [comment]
`@page { }` の中だと、`margin-outside` などは動作しない

```css
@page {
  size: A4;
  
  margin-top: 25mm;
  margin-bottom: 21mm;

  /* 小口の余白 */
  margin-outside: 130mm; /* <- 適用されない */
  /* ノドの余白 */
  margin-inside: 25mm;  
}
```

一方で、`@page :left { }` の中だと、`margin-outside` は動く。
